-- G6 Labs — Clear and reload tasks from CSV
-- Run in Supabase SQL Editor

-- Step 1: Clear existing tasks
DELETE FROM task_completions;
DELETE FROM tasks;

-- Step 2: Insert 55 tasks from CSV
INSERT INTO tasks (title, description, assignee, priority, category, frequency, status, created_by) VALUES
  ('Ads Monitoring — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Ang Dental', 'Client: Ang Dental', 'anisa', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Ang Dental', 'Client: Ang Dental', 'anisa', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Ang Dental', 'Client: Ang Dental', 'anisa', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Tlow Dental', 'Client: Tlow Dental', 'diva', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Tlow Dental', 'Client: Tlow Dental', 'diva', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Tlow Dental', 'Client: Tlow Dental', 'diva', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Isihat', 'Client: Isihat', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Isihat', 'Client: Isihat', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Isihat', 'Client: Isihat', 'diva', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Isihat', 'Client: Isihat', 'diva', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Isihat', 'Client: Isihat', 'diva', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Smile', 'Client: Smile', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Smile', 'Client: Smile', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Smile', 'Client: Smile', 'diva', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Smile', 'Client: Smile', 'diva', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Smile', 'Client: Smile', 'diva', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Canaan', 'Client: Canaan', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Canaan', 'Client: Canaan', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Canaan', 'Client: Canaan', 'diva', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Canaan', 'Client: Canaan', 'diva', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Canaan', 'Client: Canaan', 'diva', 'medium', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Dr. Glow', 'Client: Dr. Glow', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Dr. Glow', 'Client: Dr. Glow', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Dr. Glow', 'Client: Dr. Glow', 'diva', 'medium', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Dr. Glow', 'Client: Dr. Glow', 'diva', 'medium', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Dr. Glow', 'Client: Dr. Glow', 'diva', 'medium', 'design', 'daily', 'pending', 'system');