-- G6 Labs — Full task library (Daily + Weekly + Monthly)
-- Run in Supabase SQL Editor

DELETE FROM task_completions;
DELETE FROM tasks;

-- Inserting 119 tasks
INSERT INTO tasks (title, description, assignee, priority, category, frequency, status, created_by) VALUES
  ('Ads Monitoring — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'high', 'general', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Isihat', 'Client: Isihat', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Isihat', 'Client: Isihat', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Isihat', 'Client: Isihat', 'diva', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Isihat', 'Client: Isihat', 'diva', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Isihat', 'Client: Isihat', 'diva', 'high', 'design', 'daily', 'pending', 'system'),
  ('Ads Monitoring — Smile', 'Client: Smile', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Smile', 'Client: Smile', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Smile', 'Client: Smile', 'diva', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Smile', 'Client: Smile', 'diva', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Smile', 'Client: Smile', 'diva', 'high', 'design', 'daily', 'pending', 'system'),
  ('Simple Ads PPT Report — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Ang Dental', 'Client: Ang Dental', 'anisa', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Tlow Dental', 'Client: Tlow Dental', 'diva', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Isihat', 'Client: Isihat', 'diva', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Isihat', 'Client: Isihat', 'diva', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Simple Ads PPT Report — Smile', 'Client: Smile', 'diva', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Smile', 'Client: Smile', 'diva', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Content Generation — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Toothland Dental', 'Client: Toothland Dental', 'anisa', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Ang Dental', 'Client: Ang Dental', 'anisa', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Ang Dental', 'Client: Ang Dental', 'anisa', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Ang Dental', 'Client: Ang Dental', 'anisa', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Ang Dental', 'Client: Ang Dental', 'anisa', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Plaza Sentosa Clinic', 'Client: Plaza Sentosa Clinic', 'anisa', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Pancasila Clinic', 'Client: Pancasila Clinic', 'anisa', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Anytime Fitness Sungai Mas', 'Client: Anytime Fitness Sungai Mas', 'anisa', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Anytime Fitness Anggun City', 'Client: Anytime Fitness Anggun City', 'anisa', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Tlow Dental', 'Client: Tlow Dental', 'diva', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Tlow Dental', 'Client: Tlow Dental', 'diva', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Tlow Dental', 'Client: Tlow Dental', 'diva', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Tlow Dental', 'Client: Tlow Dental', 'diva', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Isihat', 'Client: Isihat', 'diva', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Isihat', 'Client: Isihat', 'diva', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Isihat', 'Client: Isihat', 'diva', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Isihat', 'Client: Isihat', 'diva', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Content Generation — Smile', 'Client: Smile', 'diva', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Smile', 'Client: Smile', 'diva', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Smile', 'Client: Smile', 'diva', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Smile', 'Client: Smile', 'diva', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Ads Monitoring — Canaan', 'Client: Canaan', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Canaan', 'Client: Canaan', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Canaan', 'Client: Canaan', 'diva', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Canaan', 'Client: Canaan', 'diva', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Canaan', 'Client: Canaan', 'diva', 'high', 'design', 'daily', 'pending', 'system'),
  ('Simple Ads PPT Report — Canaan', 'Client: Canaan', 'diva', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Canaan', 'Client: Canaan', 'diva', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Content Generation — Canaan', 'Client: Canaan', 'diva', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Canaan', 'Client: Canaan', 'diva', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Canaan', 'Client: Canaan', 'diva', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Canaan', 'Client: Canaan', 'diva', 'medium', 'ads', 'monthly', 'pending', 'system'),
  ('Ads Monitoring — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'high', 'ads', 'daily', 'pending', 'system'),
  ('Ads Report — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'high', 'report', 'daily', 'pending', 'system'),
  ('Answer Client Queries — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'high', 'general', 'daily', 'pending', 'system'),
  ('Check Scheduled Content Posting — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'high', 'content', 'daily', 'pending', 'system'),
  ('Follow Up Content in Design Status — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'high', 'design', 'daily', 'pending', 'system'),
  ('Simple Ads PPT Report — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'high', 'report', 'weekly', 'pending', 'system'),
  ('Check Content Posted This Week — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'high', 'content', 'weekly', 'pending', 'system'),
  ('Content Generation — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'medium', 'content', 'monthly', 'pending', 'system'),
  ('Content Approval - Send to Client — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'medium', 'general', 'monthly', 'pending', 'system'),
  ('Assign Content to Designer — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'medium', 'design', 'monthly', 'pending', 'system'),
  ('Campaign Ads Plan — Dr Glow Medi Spa', 'Client: Dr Glow Medi Spa', 'diva', 'medium', 'ads', 'monthly', 'pending', 'system');