"""Generate an INTERNAL PAYMENT VOUCHER PDF for an outgoing bank payment.

This document is deliberately and unmistakably a FEMO self-generated record.
It is NOT styled as, and must never be mistaken for, a third-party supplier
invoice. That distinction is the whole legal point of the tool.
"""
import os
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

import config

DISCLAIMER = ("Self-generated internal record. NOT a supplier tax invoice and "
              "cannot be used to claim a tax deduction on its own. Obtain the "
              "original invoice from the payee where available.")


def _fmt_date(iso):
    if not iso:
        return "-"
    try:
        y, m, d = iso.split("-")
        return f"{d}/{m}/{y}"
    except ValueError:
        return iso


def _money(amount):
    try:
        return f"{config.CURRENCY_SYMBOL} {float(amount):,.2f}"
    except (TypeError, ValueError):
        return f"{config.CURRENCY_SYMBOL} -"


def _watermark(c, width, height):
    c.saveState()
    c.setFont("Helvetica-Bold", 60)
    c.setFillColor(colors.Color(0.85, 0.85, 0.85, alpha=0.35))
    c.translate(width / 2, height / 2)
    c.rotate(45)
    c.drawCentredString(0, 0, "INTERNAL VOUCHER")
    c.restoreState()


def generate_voucher(voucher_id, txn, payee, purpose, category, out_dir=None):
    """txn: dict-like with date, description, amount, reference, source_file.

    Returns the absolute path of the written PDF.
    """
    out_dir = out_dir or config.VOUCHER_DIR
    os.makedirs(out_dir, exist_ok=True)
    voucher_no = f"FEMO-PV-{date.today():%Y%m%d}-{voucher_id}"
    fname = f"{voucher_no}.pdf"
    path = os.path.join(out_dir, fname)

    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4
    _watermark(c, width, height)

    # --- Red warning banner ---
    c.setFillColor(colors.HexColor("#b00020"))
    c.rect(15 * mm, height - 28 * mm, width - 30 * mm, 13 * mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(width / 2, height - 21 * mm,
                        f"{config.COMPANY_NAME} — INTERNAL PAYMENT VOUCHER")
    c.setFont("Helvetica", 7.5)
    c.drawCentredString(width / 2, height - 26 * mm,
                        "NOT A SUPPLIER TAX INVOICE — FOR INTERNAL ACCOUNTING USE ONLY")

    # --- Voucher meta ---
    y = height - 40 * mm
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20 * mm, y, f"Voucher No: {voucher_no}")
    c.setFont("Helvetica", 10)
    c.drawRightString(width - 20 * mm, y, f"Generated: {date.today():%d/%m/%Y}")

    # --- Fields table ---
    rows = [
        ("Payment Date", _fmt_date(txn.get("date"))),
        ("Paid To (Payee)", payee or "-"),
        ("Purpose / Description", purpose or txn.get("description") or "-"),
        ("Expense Category", category or "-"),
        ("Amount", _money(txn.get("amount"))),
        ("Bank Reference", txn.get("reference") or "-"),
        ("Bank Statement Description", (txn.get("description") or "-")[:90]),
        ("Source File", txn.get("source_file") or "-"),
        ("Bank Account", f"{config.COMPANY_BANK} {config.COMPANY_ACCOUNT_NO}"),
    ]
    y -= 12 * mm
    row_h = 9 * mm
    label_w = 55 * mm
    table_w = width - 40 * mm
    for i, (label, value) in enumerate(rows):
        ry = y - i * row_h
        c.setStrokeColor(colors.HexColor("#cccccc"))
        c.rect(20 * mm, ry - row_h + 2 * mm, table_w, row_h, fill=0, stroke=1)
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(colors.HexColor("#333333"))
        c.drawString(22 * mm, ry - row_h + 5 * mm, label)
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.black)
        c.drawString(20 * mm + label_w, ry - row_h + 5 * mm, str(value))

    # --- Disclaimer block ---
    dy = y - len(rows) * row_h - 12 * mm
    c.setFillColor(colors.HexColor("#fff3cd"))
    c.rect(20 * mm, dy - 18 * mm, table_w, 20 * mm, fill=1, stroke=0)
    c.setFillColor(colors.HexColor("#664d03"))
    c.setFont("Helvetica-Oblique", 8)
    _wrap(c, DISCLAIMER, 22 * mm, dy - 5 * mm, table_w - 4 * mm, 8)

    # --- Footer ---
    c.setFillColor(colors.HexColor("#888888"))
    c.setFont("Helvetica", 7)
    c.drawCentredString(width / 2, 12 * mm,
                        f"Generated by FEMO Reconcile Tool on {date.today():%d/%m/%Y} "
                        "| Internal accounting record | NOT FOR LHDN SUBMISSION")
    c.showPage()
    c.save()
    return path


def _wrap(c, text, x, y, max_width, font_size, leading=10):
    from reportlab.pdfbase.pdfmetrics import stringWidth
    words = text.split()
    line = ""
    cy = y
    for w in words:
        trial = (line + " " + w).strip()
        if stringWidth(trial, "Helvetica-Oblique", font_size) > max_width:
            c.drawString(x, cy, line)
            cy -= leading
            line = w
        else:
            line = trial
    if line:
        c.drawString(x, cy, line)
